[config]
baseId = "ken"
resourceId = ""

[n-dex]
p-name = "Ken"
p-description = '''
### Description
A organizational tool for structured data with Git.  

### Interesting Links:  
[Specification Links | JSON Schema](http://json-schema.org/specification-links.html)  
https://tools.ietf.org/html/draft-handrews-json-schema-validation-01  
https://tools.ietf.org/html/draft-handrews-json-schema-hyperschema-01  
[GitHub - toml-lang/toml: Tom’s Obvious, Minimal Language](https://github.com/toml-lang/toml)  
[Show HN: Eno – A lightning fast, user-friendly YAML/TOML alternative | Hacker News](https://news.ycombinator.com/item?id=17765426)  
[Online TOML to JSON converter](https://www.randomerrata.com/articles/2013/online-toml-to-json-converter/)  
[Linked data - Wikipedia](https://en.wikipedia.org/wiki/Linked_data)  
[Slowly changing dimension - Wikipedia](https://en.wikipedia.org/wiki/Slowly_changing_dimension)  
[Semantic triple - Wikipedia](https://en.wikipedia.org/wiki/Semantic_triple)  
[Triplestore - Wikipedia](https://en.wikipedia.org/wiki/Triplestore)  
[Named graph - Wikipedia](https://en.wikipedia.org/wiki/Named_graph)  
[Entity–attribute–value model - Wikipedia](https://en.wikipedia.org/wiki/Entity%E2%80%93attribute%E2%80%93value_model)  
[Wikidata task force report](https://docs.google.com/document/d/1ZsOyw2sOD3a7xJQ6XCSYDGjZUPxGGl8tuvC7vvtlJRU/edit)
https://en.wikipedia.org/wiki/Semantic_network
https://en.wikipedia.org/wiki/Cognition_Network_Technology
https://en.wikipedia.org/wiki/SNOMED_CT
https://en.wikipedia.org/wiki/Universal_Networking_Language
https://en.wikipedia.org/wiki/Federated_database_system
https://en.wikipedia.org/wiki/IndieWeb
https://github.com/kustomzone/awesome-solid
https://remotestorage.io
https://news.ycombinator.com/item?id=17660131ou
https://hashbase.io
https://github.com/u12206050/jsonZipper
https://github.com/glennsl/bucklescript-cookbook#create-a-map-data-structure-add-or-replace-an-entry-and-print-each-keyvalue-pair


### N3 Resources
http://rdf.js.org/N3.js/

http://n3.restdesc.org/n3

Note that they have rules:
http://n3.restdesc.org/rules/

https://github.com/rdfjs/N3.js/blob/v0.11.3/README.md#triple-representation
https://www.w3.org/DesignIssues/N3Resources
https://www.ted.com/talks/tim_berners_lee_on_the_next_web?fbclid=IwAR2jO8RTq3tHvpfysXu7VNNy-FBRjEZQIi7EbUwg8TjYSYdOdOgOSxUFMlM


## Text/react resources
https://unified.js.org
https://ar.al/2018/08/04/multiwriter-dat-could-power-the-next-web/
https://gist.github.com/pfrazee/8eb85d7bb33efb52c7d6d1a2e639d979


## Exocortex information
https://www.youtube.com/watch?v=g6JGbZxN66Y
'''
